---
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: true

- name: Creat dnsmasq configuration directory
  file:
    path: /usr/local/etc/dnsmasq.d
    state: directory
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
