---
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present
  tags:
    - install
    - dnsmasq

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: true
  tags:
    - install
    - dnsmasq

- name: Creat dnsmasq configuration directory
  file:
    path: /usr/local/etc/dnsmasq.d
    state: directory
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  tags:
    - install
    - dnsmasq

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: true
  tags:
    - install
    - dnsmasq
