---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- name: Setup Consul users and groups
  include_tasks: users.yml
  tags:
    - install

- name: Setup Consul directories
  include_tasks: dirs.yml
  tags:
    - install

- name: Fetch and extract Consul binary
  unarchive:
    src: "{{ consul_download_url }}"
    dest: /tmp
    remote_src: yes
  tags:
    - install

- name: Copy Consul binary to bin directory
  copy:
    src: /tmp/consul
    dest: "{{ consul_bin_path }}/consul"
    remote_src: yes
  tags:
    - install

- name: Change ownership of Consul binary
  file:
    path: "{{ consul_bin_path }}/consul"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - install

- name: Remove Consul downloads
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/consul.zip
    - /tmp/consul
  tags:
    - install
