---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup Consul users and groups
  include_tasks: users.yml

- name: Setup Consul directories
  include_tasks: dirs.yml

- name: Fetch and extract Consul binary
  unarchive:
    src: "{{ consul_download_url }}"
    dest: /tmp
    remote_src: yes

- name: Create Consul install directory
  file:
    path: "{{ consul_install_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: Copy Consul binary to install directory
  copy:
    src: /tmp/consul
    dest: "{{ consul_bin_path }}/consul"
    remote_src: yes

- name: Change ownership of Consul binary
  file:
    path: "{{ consul_bin_path }}/consul"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755

- name: Remove Consul downloads
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/consul.zip
    - /tmp/consul
