---
- name: Add Envoy repository
  shell:
    cmd: "yum-config-manager --add-repo {{ envoy_repo_url }}"
  tags:
    - install_envoy

- name: Install Envoy
  yum:
    name: "{{ envoy_package_name }}"
    state: present
  tags:
    - install_envoy

- name: Lock Envoy version
  shell:
    cmd: "yum versionlock getenvoy-envoy-*"
  tags:
    - install_envoy
