---
- name: Install Consul
  include_tasks: install.yml
  tags:
    - install

- name: Configure Consul
  include_tasks: configure.yml
  tags:
    - configure

- name: Install dnsmasq
  include_tasks: install_dnsmasq.yml
  tags:
    - install_dnsmasq

- name: Configure dnsmasq
  include_tasks: configure_dnsmasq.yml
  tags:
    - configure_dnsmasq
    
- name: Install Envoy
  include_tasks: install_envoy.yml
  tags:
   - install_envoy

- name: Configure Envoy
  include_tasks: configure_envoy.yml
  tags:
    - configure_envoy
