---
- name: Converge
  hosts: all
  become: true

  tasks:
  - name: Copy example service applications (1)
    copy:
      src: "files/envoy/{{ ansible_hostname }}/counting-service_linux_amd64"
      dest: "/home/vagrant/counting-service_linux_amd64"
      owner: "vagrant"
      group: "vagrant"
      mode: u=rwx,g=rx,o=rx
    tags:
      - configure_envoy

  - name: Copy example service applications (2)
    copy:
      src: "files/envoy/{{ ansible_hostname }}/dashboard-service_linux_amd64"
      dest: "/home/vagrant/dashboard-service_linux_amd64"
      owner: "vagrant"
      group: "vagrant"
      mode: u=rwx,g=rx,o=rx
    tags:
      - configure_envoy

  vars:
    # Role: rhsm
    rhsm_username: "{{ lookup('env', 'RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'RHSM_PASSWORD') }}"
    rhsm_auto_attach: true
    rhsm_server_proxy_hostname: "{{ lookup('env', 'http_proxy_hostname') }}"
    rhsm_server_proxy_port: "{{ lookup('env', 'http_proxy_port') }}"
    rhsm_server_proxy_user: "{{ lookup('env', 'http_proxy_user') }}"
    rhsm_server_proxy_password: "{{ lookup('env', 'http_proxy_password') }}"
    rhsm_consumer_name: "nycrecords_{{ '%Y%m%d_%H%M%s' | strftime(ansible_date_time.epoch) }}"

    # Role: Consul
    ansible_host_os_type: "darwin"
    consul_bootstrap: true
    consul_client_address: "0.0.0.0"
    consul_server: true
    service_files:
      counting: 
        service_definition: "counting.hcl"
        service_id: "counting-1"
      dashboard: 
        service_definition: "dashboard.hcl"
        service_id: "dashboard"
        connect_options: "-admin-bind localhost:19001"
    domain_name_servers: 
      - 8.8.8.8
      - 4.4.4.4
      - 1.1.1.1

  roles:
    - role: nycrecords.rhsm
      tags:
        - always
    - role: ansible-role-consul
